#!/usr/bin/env bash
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export GRAPHITE_IMAGE=${GRAPHITE_IMAGE:="$(awk -F '[ :]' '{print $2}' "${_DIR}/Dockerfile")"}
export GRAPHITE_IMAGE_VERSION=${GRAPHITE_IMAGE_VERSION:="$(awk -F '[ :]' '{print $3}' "${_DIR}/Dockerfile")"}
export GRAPHITE_ROOT=${GRAPHITE_ROOT:="$DOKKU_LIB_ROOT/services/grafana-graphite-statsd"}
export GRAPHITE_HOST_ROOT=${GRAPHITE_HOST_ROOT:=$GRAPHITE_ROOT}

export PLUGIN_UNIMPLEMENTED_SUBCOMMANDS=("backup" "backup-auth" "backup-deauth" "backup-schedule" "backup-schedule-cat" "backup-set-encryption" "backup-unschedule" "backup-unset-encryption" "clone" "connect" "export" "import")
export PLUGIN_COMMAND_PREFIX="graphite"
export PLUGIN_CONFIG_ROOT=${PLUGIN_CONFIG_ROOT:="$DOKKU_LIB_ROOT/config/$PLUGIN_COMMAND_PREFIX"}
export PLUGIN_DATA_ROOT=$GRAPHITE_ROOT
export PLUGIN_DATA_HOST_ROOT=$GRAPHITE_HOST_ROOT
export PLUGIN_DATASTORE_PORTS=(8125 8126 80 81 2003)
export PLUGIN_DATASTORE_WAIT_PORT=80
export PLUGIN_DEFAULT_ALIAS="STATSD"
export PLUGIN_DISABLE_PULL=${GRAPHITE_DISABLE_PULL:=}
export PLUGIN_DISABLE_PULL_VARIABLE="GRAPHITE_DISABLE_PULL"
export PLUGIN_ALT_ALIAS="DOKKU_STATSD"
export PLUGIN_IMAGE=$GRAPHITE_IMAGE
export PLUGIN_IMAGE_VERSION=$GRAPHITE_IMAGE_VERSION
export PLUGIN_SCHEME="statsd"
export PLUGIN_SERVICE="Graphite"
export PLUGIN_VARIABLE="STATSD"
export PLUGIN_BASE_PATH="$PLUGIN_PATH"
export PLUGIN_CONFIG_SUFFIX="config"
if [[ -n $DOKKU_API_VERSION ]]; then
  export PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi

export PLUGIN_BUSYBOX_IMAGE="busybox:1.31.1-uclibc"
export PLUGIN_AMBASSADOR_IMAGE="dokku/ambassador:0.3.3"
export PLUGIN_S3BACKUP_IMAGE="dokku/s3backup:0.10.3"
export PLUGIN_WAIT_IMAGE="dokku/wait:0.4.3"
