#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-nginx-expose-cmd() {
  declare desc="expose the $PLUGIN_SERVICE service's grafana via an nginx vhost"
  local cmd="$PLUGIN_COMMAND_PREFIX:nginx-expose" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1

  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" invoke "$PLUGIN_COMMAND_PREFIX" nginx-expose "$@"
}

service-nginx-expose-cmd "$@"
