#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

service-nginx-unexpose-cmd() {
  declare desc="unexpose the $PLUGIN_SERVICE service's grafana"
  local cmd="$PLUGIN_COMMAND_PREFIX:nginx-unexpose" argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1

  "${DOKKU_LIB_ROOT}/data/${PLUGIN_COMMAND_PREFIX}/dokku-datastore" invoke "$PLUGIN_COMMAND_PREFIX" nginx-unexpose "$@"
}

service-nginx-unexpose-cmd "$@"
